server:
  port: 8082

spring:
  application:
    name: catalog-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

catalog:
  movie-service:
    url: http://localhost:8081

message: Pruebas perfil dev
